#!/usr/bin/env python3
"""Generate hardware measurement protocols (English) from the hardware passport and
the emulated E00/E09 results -> hardware/measurement_protocols.md"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results"
hw = json.load(open(ROOT / "configs" / "hardware_bench_12v.json"))
S = json.load(open(RES / "summary.json"))
cal = json.load(open(RES / "calibration" / "E00_calibration.json"))
cap = S["capacity"]
U = S["uncertainty"]
f = lambda x, n=3: f"{x:.{n}f}"  # noqa: E731
LOC = {"M0": "bus after generation source", "M1": "battery branch (signed current)", "M2": "critical branch input",
       "M3": "critical load terminals", "M4": "auxiliary branch input", "M5": "auxiliary load terminals",
       "REF": "independent battery channel, separate RPi4 logger"}

L = []
w = L.append
w("# Measurement Protocols — Bench DT-NODE01-12V\n")
w("Generated by `scripts/make_protocols.py` from the hardware passport `configs/hardware_bench_12v.json` and the results of the "
  "emulated campaign. Column **EMU** holds values obtained on emulated instruments with the same datasheet characteristics; "
  "column **PHYS** is left blank to be filled during physical execution. An empty cell means *no result*, never zero.\n")
w(f"Evidence class of EMU values: *{S['evidence_class']}*. Configuration hash: `{S['config_sha256'][:16]}…`.\n")

w("## P-1. Measurement-channel passport (derived from component characteristics)\n")
w("| Channel | Location | Meter / shunt | Current full scale, A | Current LSB, mA | Voltage LSB, mV | Max zero offset, mA | Max uncalibrated gain error, % | Max shunt power, W | Calibration levels, A |")
w("|---|---|---|---:|---:|---:|---:|---:|---:|---|")
for r in S["channels"]:
    w(f"| {r['channel']} | {LOC[r['channel']]} | {r['meter']} / {r['shunt']} ({f(r['r_shunt_mohm'], 1)} mΩ) | {f(r['i_full_scale_a'], 1)} | "
      f"{f(r['i_lsb_ma'], 3)} | {f(r['v_lsb_mv'], 4)} | ±{f(r['offset_max_ma'], 2)} | ±{f(r['uncal_gain_err_max_pct'], 2)} | "
      f"{f(r['p_shunt_max_w'], 2)} | {', '.join(f(x, 2) for x in r['calibration_levels_a'])} |")
w("\nAcceptance limits (protocol §8.1): voltage ≤ 0.5 % of reading; current ≤ 1 % of reading, near zero an absolute limit of "
  "5·LSB + offset; energy ≤ 2 % on a control integral.\n")

w("## P-2. E00 — zero and coefficient calibration\n")
w("Procedure: warm up per instrument manual; zero with no power flow ≥ 60 s (600 samples at 10 Hz); five levels across the working "
  "range (charge and discharge for M1/REF); coefficients `I_cal = a·I_raw + b` fitted on levels 1, 3, 5 and verified on levels 2, 4; "
  "repeat zero and one level after the campaign (drift).\n")
w("| Channel | Raw zero, mA EMU | a EMU | b, mA EMU | Max verification residual, % EMU | Criterion ≤ 1 % | a PHYS | b PHYS | Residual PHYS | Signature |")
w("|---|---:|---:|---:|---:|---|---|---|---|---|")
for n, c in cal.items():
    w(f"| {n} | {f(c['zero_offset_raw_a'] * 1e3, 2)} | {f(c['a_i'], 5)} | {f(c['b_i'] * 1e3, 2)} | {f(c['max_verification_rel'] * 100, 3)} | "
      f"{'pass' if c['pass_current'] else 'FAIL'} | | | | |")
w("\n### P-2.1. Calibration levels (EMU), channels M1 and REF\n")
for n in ("M1", "REF"):
    w(f"**{n}**\n")
    w("| Level, A | Standard, A | DUT raw, A | DUT SD, mA | DUT calibrated, A | Residual, mA | Residual, % | Role | Saturated |")
    w("|---:|---:|---:|---:|---:|---:|---:|---|---|")
    for k, r in enumerate(cal[n]["levels"]):
        w(f"| {f(r['level_a'], 2)} | {f(r['i_std'], 4)} | {f(r['i_dut_mean'], 4)} | {f(r['i_dut_sd'] * 1e3, 2)} | {f(r['i_cal'], 4)} | "
          f"{f(r['residual_a'] * 1e3, 2)} | {f(r['residual_rel'] * 100, 3)} | {'fit' if k in (0, 2, 4) else 'verification'} | {'yes' if r['saturated'] else 'no'} |")
    w("")

w("## P-3. Uncertainty budget (k = 2) of a calibrated 1-s value\n")
w("Components (k = 1): reference standard, calibration residual, quantisation, noise of the 1-s mean (10 samples), shunt TCR at "
  "ΔT = 5 °C, residual offset after zero calibration; power combines as `(u_P/P)² = (u_U/U)² + (u_I/I)²` (protocol §16.5).\n")
w("| Channel | Operating I, A | U_I (k=2), mA | U_I, % of reading | U_U, % | U_P, % | Dominant current component |")
w("|---|---:|---:|---:|---:|---:|---|")
for n, rows in U.items():
    for r in rows:
        dom = max(r["components_i"].items(), key=lambda kv: kv[1])[0]
        w(f"| {n} | {f(r['i_op_a'], 1)} | {f(r['U_i_a_k2'] * 1e3, 2)} | {f(abs(r['U_i_rel_k2']) * 100, 3)} | {f(r['U_v_rel_k2'] * 100, 3)} | "
          f"{f(abs(r['U_p_rel_k2']) * 100, 3)} | {dom} |")
w("\nConsequence for SOC: the residual M1 zero offset of about ±1.7 mA after calibration gives ≤ 0.1 pp drift per 24 h at Q ≈ 38.4 Ah. "
  "On 6-hour runs the initial-SOC uncertainty (±0.4 pp, 1σ) and Q_ref (≈ 0.1 %) dominate over the current term.\n")

w("## P-4. E09 — capacity of the working interval\n")
w("| Parameter | Condition / tolerance | EMU | PHYS |")
w("|---|---|---:|---|")
rows = [("Charge to 'full'", "CC 20 A → CV 14.2 V, tail 2 A (0.05C)", "done", ""),
        ("Rest", "30 min", "30 min", ""),
        ("Discharge", "CC 10 A (0.25C) to 11.2 V under load", f"{f(cap['discharge_time_h'], 2)} h", ""),
        ("Q_ref (REF), Ah", "—", f(cap["q_ref_ah"], 3), ""),
        ("Q_M1 (M1), Ah", "|Q_M1 − Q_ref| ≤ 1 %", f(cap["q_m1_ah"], 3), ""),
        ("E_ref, Wh", "—", f(cap["e_ref_wh"], 1), ""),
        ("η_Q (REF) = Ah_out/Ah_in", "0.98–1.00 for LiFePO₄", f(cap["eta_q_ref"], 4), ""),
        ("Temperature", "22 ± 2 °C", "22.0", ""),
        ("Hidden true capacity (emulation only)", "not available in a physical test", f(cap["true_capacity_ah_hidden"], 2), "—")]
for r in rows:
    w(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} |")
w("\nNote: this determines the capacity of the **working interval** (14.2 V / 2 A … 11.2 V at 10 A), not the full nameplate capacity (protocol §8.2).\n")

w("## P-5. Pre-run checklist (protocol §21.2)\n")
for item in ["Datasheets and operating limits of the actual units stored (P-1 filled in)",
             "Mode physical / chil_realtime / controller_replay / sil fixed in the run configuration",
             "Polarity, fuses MIDI 40 A / ATO 25/5/7.5 A and Blue Sea 6006 checked",
             "All battery current passes through M1 and REF (test: 5 A from RD6018 → |I_M1 − I_REF| ≤ 1 %)",
             "Sign test: 18 W discharge → I_M1 > 0, I_REF > 0; 60 W charge → both < 0",
             "Zero of M0–M5, REF: |I| within the P-1 limit after 60 s",
             "Relay: OFF command → M4 < 0.05 A within ≤ 1 s; ON command → M4 > 1.4 A within ≤ 1 s (EMU: median 200 ms)",
             "Watchdog: heartbeat stopped for 6 s → DEGRADED, relay OFF",
             "Initial SOC_ref within ±1 pp; battery temperature 20–24 °C",
             "Clocks synchronised (SNTP), residual offset recorded (EMU: ±15 ms)",
             "PC, ESP32 and RPi4 on UPS; ≥ 1 GB free for logs",
             "run_id, boot_id, configuration/firmware/profile hashes entered in the run protocol"]:
    w(f"- [ ] {item}")

w("\n## P-6. Run protocols\n")
w("For each of the " + str(len(S["runs"])) + " emulated runs a protocol in the §21.3 format is stored in "
  "`results/protocols/<run_id>.txt`; raw logs in `results/raw/<run_id>/` (telemetry_10s.csv, events.csv, commands.csv, edge_log.csv); "
  "checksums in `results/checksums.sha256`. For a physical run use the same template with MODE set to `physical` and the operator fields filled in.\n")
w("| run_id | Scenario | Policy | Duration, h | Stop reason | Coverage, % | SOC MAE, pp | Lighting served, Wh | Critical unserved, Wh |")
w("|---|---|---|---:|---|---:|---:|---:|---:|")
for r in S["runs"]:
    if r["scenario_id"] == "E05" and r["repeat"] > 0:
        continue
    w(f"| `{r['run_id']}` | {r['scenario_id']} | {r['policy']} | {f(r['duration_h'], 2)} | {r['stop_reason']} | {f(r['coverage_pct'], 2)} | "
      f"{f(r['mae_soc_pp'], 2)} | {f(r['aux_served_wh'], 1)} | {f(r['critical_unserved_wh'], 1)} |")
w("\n(E05: block R00 shown; all 10 blocks are in `results/metrics_runs.csv`.)\n")

w("## P-7. Deviation card (template, protocol §21.6)\n")
w("```text\nDEVIATION_ID:\nRUN_ID:\nWHEN_DETECTED:\nWHAT_HAPPENED:\nAFFECTED_CHANNELS_AND_INTERVAL:\nRAW_DATA_PRESERVED: yes / no with reason\n"
  "ACTION_TAKEN:\nEFFECT_ON_PRIMARY_METRIC:\nELIGIBLE_FOR_ENERGY_ANALYSIS:\nELIGIBLE_FOR_TIMING_ANALYSIS:\nREPEAT_REQUIRED:\nAPPROVED_BY:\n```\n")
(ROOT / "hardware" / "measurement_protocols.md").write_text("\n".join(L), encoding="utf-8")
print("written hardware/measurement_protocols.md")
