"""Data foundation: provenance, stable seeding, curation controls, source connectors.

Implements Section 3 of the paper:

* Eq. (1)  completeness of a taxon / character in a morphological matrix;
* Eq. (2)  sampling weight of a clade, used when counting independent origins;
* the provenance record pi = (source, version, license, tag, uri, date, r, u)
  of Section 3.3 with its five tags MEASURED / MODELED / PROXY / EXTERNAL /
  SYNTHETIC;
* content-addressed corpus snapshots;
* connectors that expose the Open Tree of Life v3, PBDB v1.2 and MorphoBank
  endpoints.

No biological records are bundled with the package.  The connectors build and
return request URLs; they perform network access only when a caller explicitly
opts in (``allow_network=True``), so that the whole package can be executed and
audited offline (Section 5).
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np

__all__ = [
    "PACKAGE_VERSION",
    "ProvenanceTag",
    "Provenance",
    "stable_seed",
    "taxon_completeness",
    "character_completeness",
    "admit_by_completeness",
    "sampling_weight",
    "CorpusSnapshot",
    "OfflineError",
    "SourceConnector",
    "OpenTreeOfLifeConnector",
    "PaleobiologyDatabaseConnector",
    "MorphoBankConnector",
    "default_connectors",
]

PACKAGE_VERSION = "0.1.0"

#: Value used by Eq. (1) to mark an unobserved cell of a character matrix.
MISSING = np.nan


class ProvenanceTag(str, Enum):
    """The five provenance tags of Section 3.3.

    The ordering is from strongest to weakest evidence; :meth:`weakest`
    propagates a tag through a derived quantity so that a MODELED result can
    never be mistaken for a MEASURED one.
    """

    MEASURED = "MEASURED"
    MODELED = "MODELED"
    PROXY = "PROXY"
    EXTERNAL = "EXTERNAL"
    SYNTHETIC = "SYNTHETIC"

    @classmethod
    def order(cls) -> List["ProvenanceTag"]:
        return [cls.MEASURED, cls.MODELED, cls.PROXY, cls.EXTERNAL, cls.SYNTHETIC]

    @classmethod
    def weakest(cls, tags: Iterable["ProvenanceTag"]) -> "ProvenanceTag":
        """Return the weakest tag of ``tags`` (the tag a derived value inherits)."""
        order = cls.order()
        tags = list(tags)
        if not tags:
            raise ValueError("weakest() requires at least one tag")
        return max(tags, key=order.index)


@dataclass(frozen=True)
class Provenance:
    """Provenance record ``pi = (source, version, license, tag, uri, date, r, u)``.

    Parameters
    ----------
    source, version, license, uri, date:
        Bibliographic / archival identification of the datum.
    tag:
        One of the five :class:`ProvenanceTag` values.
    r:
        Reconstruction flag.  ``r=1`` marks an ancestral state produced by a
        comparative method rather than observed on a specimen; reconstructed
        records are down-weighted by the evidence score (Eq. 13).
    u:
        Uncertainty estimate attached to the datum, in ``[0, 1]``.
    method:
        Reconstruction method, required when ``r == 1``.
    """

    source: str
    version: str
    license: str
    tag: ProvenanceTag
    uri: str = ""
    date: str = field(default_factory=lambda: _dt.date.today().isoformat())
    r: int = 0
    u: float = 0.0
    method: str = ""

    def __post_init__(self) -> None:
        if self.r not in (0, 1):
            raise ValueError("reconstruction flag r must be 0 or 1")
        if not 0.0 <= float(self.u) <= 1.0:
            raise ValueError("uncertainty u must lie in [0, 1]")
        if self.r == 1 and not self.method:
            raise ValueError("a reconstructed record (r=1) must name its method")
        object.__setattr__(self, "tag", ProvenanceTag(self.tag))

    @property
    def reconstructed(self) -> bool:
        return self.r == 1

    def as_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["tag"] = self.tag.value
        return d

    @classmethod
    def synthetic(cls, source: str = "evoproto.synthetic", **kwargs: Any) -> "Provenance":
        """Provenance for data generated by the package itself (demo mode)."""
        kwargs.setdefault("version", PACKAGE_VERSION)
        kwargs.setdefault("license", "MIT")
        return cls(source=source, tag=ProvenanceTag.SYNTHETIC, **kwargs)

    @classmethod
    def modeled(cls, source: str, **kwargs: Any) -> "Provenance":
        """Provenance for a number produced by a model or a surrogate evaluator."""
        kwargs.setdefault("version", PACKAGE_VERSION)
        kwargs.setdefault("license", "MIT")
        return cls(source=source, tag=ProvenanceTag.MODELED, **kwargs)

    @staticmethod
    def combine(records: Sequence["Provenance"]) -> ProvenanceTag:
        """Tag inherited by a quantity derived from ``records`` (weakest wins)."""
        return ProvenanceTag.weakest(r.tag for r in records)


def stable_seed(
    task_id: str,
    arm: str,
    replicate: int,
    version: str = PACKAGE_VERSION,
    digest_bytes: int = 4,
) -> int:
    """Derive a reproducible seed with blake2b (Section 5).

    Python's built-in :func:`hash` is randomised per process, so a seed derived
    from it is not reproducible across machines or runs.  The tuple
    ``(version, task_id, arm, replicate)`` is hashed instead, which makes every
    replicate reproducible and prevents silent seed collisions between arms.
    """
    if replicate < 0:
        raise ValueError("replicate must be non-negative")
    payload = "|".join(("evoproto", str(version), str(task_id), str(arm), str(int(replicate))))
    digest = hashlib.blake2b(payload.encode("utf-8"), digest_size=digest_bytes).digest()
    return int.from_bytes(digest, "big")


def _observed_mask(matrix: np.ndarray) -> np.ndarray:
    """Boolean mask of observed cells; NaN marks an unobserved cell."""
    arr = np.asarray(matrix, dtype=float)
    if arr.ndim != 2:
        raise ValueError("a character matrix must be two-dimensional (taxa x characters)")
    return ~np.isnan(arr)


def taxon_completeness(matrix: np.ndarray) -> np.ndarray:
    r"""Eq. (1), taxon completeness :math:`c_i = p^{-1}\sum_j 1[x_{ij}\ \text{observed}]`."""
    obs = _observed_mask(matrix)
    return obs.mean(axis=1)


def character_completeness(matrix: np.ndarray) -> np.ndarray:
    r"""Eq. (1), character completeness :math:`c_j = n^{-1}\sum_i 1[x_{ij}\ \text{observed}]`."""
    obs = _observed_mask(matrix)
    return obs.mean(axis=0)


def admit_by_completeness(
    matrix: np.ndarray,
    c_min: float,
    query_characters: Optional[Sequence[int]] = None,
) -> np.ndarray:
    """Admission rule of Section 3.2: keep taxa with ``c_i >= c_min``.

    Completeness is evaluated over ``query_characters`` only — the paper admits
    a record "for the characters that participate in the query" — so a taxon
    that is sparsely scored elsewhere is still usable for a query it covers.
    """
    if not 0.0 <= c_min <= 1.0:
        raise ValueError("c_min must lie in [0, 1]")
    arr = np.asarray(matrix, dtype=float)
    if query_characters is not None:
        cols = list(query_characters)
        if not cols:
            raise ValueError("query_characters must not be empty")
        arr = arr[:, cols]
    return taxon_completeness(arr) >= c_min


def sampling_weight(n_observed: float, n_accepted: float) -> float:
    r"""Eq. (2), :math:`w_k = \min(1, n_k^{\mathrm{obs}} / \hat n_k)`.

    ``n_observed`` is the number of sampled taxa of the clade and ``n_accepted``
    its accepted species richness (OTOL taxonomy).  Weighting the count of
    independent origins by ``w`` keeps an unevenly sampled clade from carrying
    the same confidence as a well-sampled one.
    """
    if n_accepted <= 0:
        raise ValueError("accepted richness must be positive")
    if n_observed < 0:
        raise ValueError("observed sample size must be non-negative")
    return float(min(1.0, n_observed / n_accepted))


def _canonical(obj: Any) -> Any:
    """Convert numpy / enum / dataclass content into JSON-canonical form."""
    if isinstance(obj, ProvenanceTag):
        return obj.value
    if isinstance(obj, Provenance):
        return obj.as_dict()
    if isinstance(obj, np.generic):
        return obj.item()
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, Mapping):
        return {str(k): _canonical(v) for k, v in sorted(obj.items(), key=lambda kv: str(kv[0]))}
    if isinstance(obj, (list, tuple)):
        return [_canonical(v) for v in obj]
    return obj


@dataclass(frozen=True)
class CorpusSnapshot:
    """A content-addressed snapshot of the corpus (Section 3.3).

    A recommendation refers to the snapshot hash under which it was generated;
    the hash is a blake2b digest over the canonical JSON serialisation of the
    payload, so it is stable across machines and Python versions.
    """

    name: str
    payload: Mapping[str, Any]
    created: str = field(default_factory=lambda: _dt.datetime.now(_dt.timezone.utc).isoformat())

    @property
    def canonical_json(self) -> str:
        return json.dumps(_canonical(dict(self.payload)), sort_keys=True, separators=(",", ":"))

    @property
    def hash(self) -> str:
        return hashlib.blake2b(self.canonical_json.encode("utf-8"), digest_size=16).hexdigest()

    def as_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "created": self.created,
            "hash": self.hash,
            "payload": _canonical(dict(self.payload)),
        }


class OfflineError(RuntimeError):
    """Raised when a connector is asked to fetch while network access is off."""


@dataclass
class SourceConnector:
    """Base connector: builds request URLs, fetches only when allowed.

    The package ships in SYNTHETIC mode: ``allow_network`` defaults to ``False``
    so that a reviewer can execute every code path offline.  Enabling it does
    not bundle any record — the caller remains responsible for the licence of
    whatever it retrieves.
    """

    name: str
    base_url: str
    api_version: str
    license: str
    allow_network: bool = False
    timeout: float = 30.0

    def endpoint(self, path: str) -> str:
        return f"{self.base_url.rstrip('/')}/{path.lstrip('/')}"

    def provenance(self, uri: str, tag: ProvenanceTag = ProvenanceTag.EXTERNAL, **kw: Any) -> Provenance:
        return Provenance(
            source=self.name,
            version=self.api_version,
            license=self.license,
            tag=tag,
            uri=uri,
            **kw,
        )

    def fetch(self, url: str, payload: Optional[Mapping[str, Any]] = None) -> Any:
        """GET/POST ``url``; raises :class:`OfflineError` unless opted in."""
        if not self.allow_network:
            raise OfflineError(
                f"{self.name}: network access is disabled. Instantiate the connector with "
                "allow_network=True to retrieve records under their own licence."
            )
        import urllib.request  # imported lazily: offline use must not need it

        data = None
        headers = {"User-Agent": f"evoproto/{PACKAGE_VERSION}"}
        if payload is not None:
            data = json.dumps(dict(payload)).encode("utf-8")
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(url, data=data, headers=headers)
        with urllib.request.urlopen(request, timeout=self.timeout) as response:  # noqa: S310
            return json.loads(response.read().decode("utf-8"))


class OpenTreeOfLifeConnector(SourceConnector):
    """Open Tree of Life API v3: name resolution and induced subtrees."""

    def __init__(self, allow_network: bool = False) -> None:
        super().__init__(
            name="Open Tree of Life",
            base_url="https://api.opentreeoflife.org/v3",
            api_version="v3",
            license="CC0-1.0 (synthetic tree); source trees under their own terms",
            allow_network=allow_network,
        )

    def match_names_request(self, names: Sequence[str]) -> Tuple[str, Dict[str, Any]]:
        """Build the ``tnrs/match_names`` request that resolves names to OTT ids."""
        return self.endpoint("tnrs/match_names"), {"names": list(names)}

    def induced_subtree_request(self, ott_ids: Sequence[int]) -> Tuple[str, Dict[str, Any]]:
        """Build the ``tree_of_life/induced_subtree`` request for a taxon set."""
        return self.endpoint("tree_of_life/induced_subtree"), {"ott_ids": [int(i) for i in ott_ids]}


class PaleobiologyDatabaseConnector(SourceConnector):
    """Paleobiology Database data service v1.2: fossil occurrences."""

    def __init__(self, allow_network: bool = False) -> None:
        super().__init__(
            name="Paleobiology Database",
            base_url="https://paleobiodb.org/data1.2",
            api_version="v1.2",
            license="CC-BY-4.0",
            allow_network=allow_network,
        )

    def occurrences_request(
        self,
        base_name: str,
        interval: Optional[str] = None,
        show: Sequence[str] = ("coords", "class", "refattr"),
    ) -> Tuple[str, Dict[str, Any]]:
        """Build the ``occs/list`` query for a clade and (optionally) an interval."""
        params: Dict[str, Any] = {"base_name": base_name, "show": ",".join(show)}
        if interval:
            params["interval"] = interval
        return self.endpoint("occs/list.json"), params


class MorphoBankConnector(SourceConnector):
    """MorphoBank: per-project morphological matrices (NEXUS/TNT downloads)."""

    def __init__(self, allow_network: bool = False) -> None:
        super().__init__(
            name="MorphoBank",
            base_url="https://morphobank.org",
            api_version="project-download",
            license="per-project (commonly CC0 after publication)",
            allow_network=allow_network,
        )

    def matrix_download_request(self, project_id: int, matrix_id: int) -> Tuple[str, Dict[str, Any]]:
        """Build the per-project matrix download reference (manual curation step)."""
        url = self.endpoint(f"permalink/?P{int(project_id)}")
        return url, {"project_id": int(project_id), "matrix_id": int(matrix_id), "format": "nexus"}


def default_connectors(allow_network: bool = False) -> Dict[str, SourceConnector]:
    """The three source connectors of Table 2, offline by default."""
    return {
        "otol": OpenTreeOfLifeConnector(allow_network=allow_network),
        "pbdb": PaleobiologyDatabaseConnector(allow_network=allow_network),
        "morphobank": MorphoBankConnector(allow_network=allow_network),
    }
