"""Data foundation: provenance, curation controls and source connectors (Section 3).

Three responsibilities live here:

1. :class:`Provenance` - the five-field record ``(source, version, license, r, u)``
   plus the five-valued :class:`Tag` that is propagated to every number the
   package computes (Section 3.3).
2. The curation controls of Section 3.2 that are expressible as functions:
   :func:`completeness` (Eq. 1) and :func:`sampling_weight` (Eq. 2).
3. Connectors that describe - and, only when explicitly enabled, issue - the
   requests against Open Tree of Life, the Paleobiology Database and
   MorphoBank (Table 2).  The default is offline: the connectors build and
   return the request descriptor so that a corpus snapshot can be assembled,
   audited and licensed deliberately rather than as a side effect of an import.

Seeding (:func:`stable_seed`) is derived with blake2b over
``(package version, task id, arm, replicate)`` rather than Python's built-in
``hash``, which is randomized per process.  This makes every replicate
reproducible across machines and prevents silent seed collisions between arms.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any

__all__ = [
    "Connector",
    "MorphoBankConnector",
    "OTOLConnector",
    "OfflineAccessError",
    "PBDBConnector",
    "Provenance",
    "RequestDescriptor",
    "Tag",
    "completeness",
    "corpus_snapshot_hash",
    "sampling_weight",
    "stable_seed",
]

SEED_BITS = 32
"""Width of the integer returned by :func:`stable_seed` (fits NumPy seeds)."""


class Tag(str, Enum):
    """Provenance tag propagated to every metric computed from a datum.

    The five values are defined in Section 3.3:

    ``MEASURED``
        Produced by a physical measurement (the only source of empirical fact
        in the framework; see Section 4.7).
    ``MODELED``
        Produced by a numerical model (analytic evaluator, FE, CFD).
    ``PROXY``
        A stand-in quantity that correlates with, but does not measure, the
        target (e.g. solid volume as a cost proxy, Eq. 18).
    ``EXTERNAL``
        Taken from an external resource under its own license and version.
    ``SYNTHETIC``
        Generated by the package for demonstration or pipeline validation; it
        supports no empirical claim whatsoever.
    """

    MEASURED = "MEASURED"
    MODELED = "MODELED"
    PROXY = "PROXY"
    EXTERNAL = "EXTERNAL"
    SYNTHETIC = "SYNTHETIC"


@dataclass(frozen=True)
class Provenance:
    """Provenance record ``p = (source, version, license, r, u)`` (Section 3.3).

    Parameters
    ----------
    source:
        Resource or publication the datum comes from (e.g. ``"PBDB"``, a DOI).
    version:
        Version, snapshot or release identifier of that source.
    license:
        License under which the datum may be redistributed.
    tag:
        One of :class:`Tag`.
    reconstructed:
        ``r`` of Section 3.3: ``True`` when the state is reconstructed by a
        comparative method rather than observed on a specimen.  Reconstructed
        states are down-weighted in evidence scoring (Eq. 13).
    uncertainty:
        ``u`` of Section 3.3, in ``[0, 1]``; ``None`` when not reported.
    retrieved:
        ISO date of retrieval (``EXTERNAL`` records should always carry one).
    identifier:
        Record-level identifier inside the source (OTT id, PBDB record id,
        MorphoBank project id, DOI).
    method:
        Reconstruction or measurement method, required when ``reconstructed``.
    note:
        Free-text remark kept in the audit trail.
    """

    source: str
    version: str
    license: str
    tag: Tag = Tag.EXTERNAL
    reconstructed: bool = False
    uncertainty: float | None = None
    retrieved: str | None = None
    identifier: str | None = None
    method: str | None = None
    note: str | None = None

    def __post_init__(self) -> None:
        if self.uncertainty is not None and not 0.0 <= float(self.uncertainty) <= 1.0:
            raise ValueError("uncertainty must lie in [0, 1]")
        if not self.source or not self.version or not self.license:
            raise ValueError("source, version and license are mandatory (Section 3.3)")
        if self.reconstructed and not self.method:
            raise ValueError(
                "a reconstructed state must record its reconstruction method "
                "(Section 3.2, observation versus reconstruction)"
            )

    @property
    def r(self) -> int:
        """Reconstruction flag as the integer used in Eq. (13)."""
        return int(self.reconstructed)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["tag"] = self.tag.value
        return d

    @classmethod
    def synthetic(cls, note: str = "generated by evoproto") -> Provenance:
        """Provenance for a number this package invented for demonstration."""
        return cls(
            source="evoproto",
            version="synthetic",
            license="MIT",
            tag=Tag.SYNTHETIC,
            note=note,
        )


def stable_seed(
    task_id: str,
    arm: str,
    replicate: int,
    package_version: str | None = None,
    bits: int = SEED_BITS,
) -> int:
    """Return a reproducible seed for one experiment cell.

    The seed is ``blake2b(package_version | task_id | arm | replicate)`` reduced
    to ``bits`` bits.  Unlike :func:`hash`, blake2b is stable across processes,
    machines and Python versions, so a replicate rerun a year later reproduces
    exactly; and because the arm is part of the digest, arms B and C never
    silently share a random stream.

    Examples
    --------
    >>> stable_seed("T1", "B", 0) == stable_seed("T1", "B", 0)
    True
    >>> stable_seed("T1", "B", 0) == stable_seed("T1", "C", 0)
    False
    """
    if replicate < 0:
        raise ValueError("replicate must be non-negative")
    if package_version is None:
        from evoproto import __version__ as package_version  # local import: cycle
    payload = "|".join([package_version, task_id, arm, str(int(replicate))])
    digest = hashlib.blake2b(payload.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, "big") % (1 << bits)


def completeness(matrix: Sequence[Sequence[Any]], missing: Any = None) -> dict[str, list[float]]:
    """Completeness of taxa and characters of a matrix (Eq. 1).

    ``matrix[i][j]`` is the state of character ``j`` in taxon ``i``; entries
    equal to ``missing`` (default ``None``; NaN also counts) are absent.

    Returns
    -------
    dict
        ``{"taxa": [c_i], "characters": [c_j]}`` with values in ``[0, 1]``.
    """
    rows = [list(r) for r in matrix]
    if not rows:
        return {"taxa": [], "characters": []}
    n_char = len(rows[0])
    if any(len(r) != n_char for r in rows):
        raise ValueError("character matrix must be rectangular")

    def present(value: Any) -> bool:
        if value is missing or value == missing:
            return False
        return not (isinstance(value, float) and value != value)  # NaN

    taxa = [sum(present(v) for v in row) / n_char for row in rows] if n_char else []
    characters = [
        sum(present(row[j]) for row in rows) / len(rows) for j in range(n_char)
    ]
    return {"taxa": taxa, "characters": characters}


def admits_record(
    completeness_value: float, threshold: float, *, name: str = "record"
) -> bool:
    """Missing-data control of Section 3.2: admit iff ``c >= c_min``."""
    if not 0.0 <= threshold <= 1.0:
        raise ValueError(f"completeness threshold for {name} must lie in [0, 1]")
    return completeness_value >= threshold


def sampling_weight(
    n_sampled: int,
    n_richness: int,
    reference_fraction: float = 0.1,
) -> float:
    """Sampling weight ``w_c`` of a clade used in convergence counting (Eq. 2).

    Morphological and fossil sampling is uneven across clades, so counting one
    unit per homology class lets a densely sampled clade inflate the apparent
    number of independent origins.  The weight caps the credit a clade receives
    at its sampling intensity relative to a corpus-level reference:

    .. math::  w_c = \\min\\bigl(1,\\; f_\\text{ref} \\,/\\, (n_c / N_c)\\bigr)

    where ``n_c`` is the number of sampled taxa, ``N_c`` the accepted species
    richness of the clade from the OTOL taxonomy, and ``f_ref`` the reference
    sampling fraction recorded in the corpus datasheet.  A clade sampled at or
    below the reference intensity keeps full weight; one sampled ten times more
    intensively contributes one tenth.

    Notes
    -----
    The functional form is an implementation choice of this reference
    implementation; it is a corpus-level hyperparameter and must be frozen in
    the pre-registration (Section 7.8) together with ``f_ref``.  See
    ``docs/paper_mapping.md`` for the open items.
    """
    if n_sampled <= 0:
        return 0.0
    if n_richness <= 0:
        raise ValueError("clade richness N_c must be positive")
    if not 0.0 < reference_fraction <= 1.0:
        raise ValueError("reference_fraction must lie in (0, 1]")
    fraction = min(1.0, n_sampled / n_richness)
    return float(min(1.0, reference_fraction / fraction))


def corpus_snapshot_hash(records: Iterable[Mapping[str, Any]]) -> str:
    """Content-addressed hash of a corpus snapshot (Section 3.3).

    Records are serialized canonically (sorted keys, no whitespace) and hashed
    with blake2b, so the hash depends on content only - not on record order or
    on the machine that assembled it.  Every recommendation refers to the
    snapshot hash under which it was generated.
    """
    hasher = hashlib.blake2b(digest_size=32)
    for blob in sorted(
        json.dumps(dict(record), sort_keys=True, separators=(",", ":"), default=str)
        for record in records
    ):
        hasher.update(blob.encode("utf-8"))
        hasher.update(b"\n")
    return hasher.hexdigest()


class OfflineAccessError(RuntimeError):
    """Raised when a connector is asked to fetch while network use is disabled."""


@dataclass(frozen=True)
class RequestDescriptor:
    """A fully specified, auditable request against an external resource."""

    source: str
    url: str
    params: Mapping[str, Any] = field(default_factory=dict)
    license: str = "see source terms"
    api_version: str = ""
    provenance_fields: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "source": self.source,
            "url": self.url,
            "params": dict(self.params),
            "license": self.license,
            "api_version": self.api_version,
            "provenance_fields": list(self.provenance_fields),
        }


class Connector:
    """Base class for the corpus connectors of Table 2.

    Connectors are *offline by default*.  :meth:`describe` returns the request
    descriptor without contacting anything; :meth:`fetch` performs the request
    only when the connector was constructed with ``allow_network=True``, and
    raises :class:`OfflineAccessError` otherwise.  This keeps the demonstration
    pipeline hermetic and forces corpus assembly to be an explicit, licensed,
    logged act.
    """

    source = "abstract"
    api_version = ""
    license = "see source terms"
    provenance_fields: tuple[str, ...] = ()

    def __init__(self, allow_network: bool = False, timeout: float = 30.0) -> None:
        self.allow_network = bool(allow_network)
        self.timeout = float(timeout)

    def _descriptor(self, url: str, params: Mapping[str, Any]) -> RequestDescriptor:
        return RequestDescriptor(
            source=self.source,
            url=url,
            params=dict(params),
            license=self.license,
            api_version=self.api_version,
            provenance_fields=self.provenance_fields,
        )

    def fetch(self, descriptor: RequestDescriptor, method: str = "GET") -> bytes:
        """Execute ``descriptor``; requires ``allow_network=True``."""
        if not self.allow_network:
            raise OfflineAccessError(
                f"{self.source} access is disabled. Construct the connector with "
                "allow_network=True and record the retrieval date, version and "
                "license in the corpus datasheet before enabling it."
            )
        import urllib.parse
        import urllib.request

        if method.upper() == "GET":
            query = urllib.parse.urlencode(descriptor.params, doseq=True)
            url = f"{descriptor.url}?{query}" if query else descriptor.url
            request = urllib.request.Request(url, method="GET")
        else:
            body = json.dumps(dict(descriptor.params)).encode("utf-8")
            request = urllib.request.Request(
                descriptor.url,
                data=body,
                method="POST",
                headers={"Content-Type": "application/json"},
            )
        with urllib.request.urlopen(request, timeout=self.timeout) as response:  # noqa: S310
            return response.read()

    def provenance(self, identifier: str | None = None, version: str | None = None) -> Provenance:
        """Provenance stub for a record retrieved through this connector."""
        return Provenance(
            source=self.source,
            version=version or self.api_version or "unversioned",
            license=self.license,
            tag=Tag.EXTERNAL,
            retrieved=_dt.date.today().isoformat(),
            identifier=identifier,
        )


class OTOLConnector(Connector):
    """Open Tree of Life v3: name resolution and induced subtrees [48, 49]."""

    source = "Open Tree of Life"
    api_version = "v3"
    license = "CC0 (synthetic tree); source trees keep their own terms"
    provenance_fields = ("synthetic_tree_version", "ott_ids", "source_tree_citations", "retrieved")
    base_url = "https://api.opentreeoflife.org/v3"

    def match_names(self, names: Sequence[str]) -> RequestDescriptor:
        """Taxonomic name resolution (``tnrs/match_names``), Section 3.2."""
        return self._descriptor(f"{self.base_url}/tnrs/match_names", {"names": list(names)})

    def induced_subtree(self, ott_ids: Sequence[int]) -> RequestDescriptor:
        """Induced subtree over resolved OTT ids (``tree_of_life/induced_subtree``)."""
        return self._descriptor(
            f"{self.base_url}/tree_of_life/induced_subtree", {"ott_ids": list(ott_ids)}
        )


class PBDBConnector(Connector):
    """Paleobiology Database data service v1.2: fossil occurrences [52, 53]."""

    source = "Paleobiology Database"
    api_version = "v1.2"
    license = "CC BY 4.0"
    provenance_fields = ("record_id", "reference_id", "age_model", "license", "retrieved")
    base_url = "https://paleobiodb.org/data1.2"

    def occurrences(
        self, base_name: str, interval: str | None = None, show: str = "coords,class,loc"
    ) -> RequestDescriptor:
        """Occurrence list (``occs/list``) for a taxon, optionally time-sliced."""
        params: dict[str, Any] = {"base_name": base_name, "show": show}
        if interval:
            params["interval"] = interval
        return self._descriptor(f"{self.base_url}/occs/list.json", params)


class MorphoBankConnector(Connector):
    """MorphoBank: per-project morphological character matrices [50, 51]."""

    source = "MorphoBank"
    api_version = "project download"
    license = "per project; recorded per matrix"
    provenance_fields = ("project_id", "matrix_version", "character_definitions", "license")
    base_url = "https://morphobank.org/index.php/Projects/Matrices"

    def matrix(self, project_id: int, matrix_format: str = "NEXUS") -> RequestDescriptor:
        """Descriptor for a matrix download in NEXUS or TNT format."""
        if matrix_format.upper() not in {"NEXUS", "TNT"}:
            raise ValueError("matrix_format must be NEXUS or TNT")
        return self._descriptor(
            f"{self.base_url}/project_id/{int(project_id)}",
            {"format": matrix_format.upper()},
        )
