#!/usr/bin/env python3
import csv, json, os
os.makedirs('tables',exist_ok=True)
def write_csv(fn, header, rows):
    with open('tables/'+fn,'w',newline='') as f:
        w=csv.writer(f); w.writerow(header); w.writerows(rows)
def write_latex(fn, caption, label, header, rows, align=None):
    n=len(header); align=align or ('l'+'c'*(n-1))
    with open('tables/'+fn,'w') as f:
        f.write('% Auto-generated by build_static_tables.py\n')
        f.write('\\begin{table}[t]\n\\centering\n\\caption{%s}\n\\label{%s}\n'%(caption,label))
        f.write('\\begin{tabular}{%s}\n\\hline\n'%align)
        f.write(' & '.join(header)+' \\\\\n\\hline\n')
        for r in rows: f.write(' & '.join(str(x) for x in r)+' \\\\\n')
        f.write('\\hline\n\\end{tabular}\n\\end{table}\n')

# ---- Environment / hardware-software table ----
env_rows=[
 ['Operating system','Ubuntu 24.04.4 LTS (Noble Numbat), Linux kernel 6.18.5, x86-64'],
 ['CPU','Intel Xeon (Cascade Lake-class) @ 2.10 GHz, 4 vCPU'],
 ['System memory','16 GiB (16,461,176 kB)'],
 ['Compiler','GNU g++ (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0'],
 ['Language standard','ISO C++17 (-std=c++17)'],
 ['Optimization flags','-O2'],
 ['Build commands','g++ -std=c++17 -O2 -o radartwin main_s1.cpp; ... ustfuse main_s2.cpp; ... fusemetrics main_s3.cpp'],
 ['Analytics runtime','Python 3.11.15 (aggregation, statistics, figures); matplotlib 3.11.1, numpy 2.4.6, scipy 1.17.1'],
 ['Threading','single-threaded C++ (no parallel user processes during latency runs)'],
 ['Experiment dates','2026-07-30'],
 ['Random seeds','20260730 - 20260759 (30 repetitions)'],
 ['Scenarios per repetition','400'],
]
write_csv('table_environment.csv',['Property','Value'],env_rows)
write_latex('table_environment.tex','Computational environment (software and hardware).','tab:environment',['Property','Value'],env_rows)

# ---- Table 2: hyperparameter configuration (from source constants) ----
t2=[
 ['DQ','Observation window length W','1 dwell (per-dwell fusion in reference impl.; sliding-window encoder of Sec. 3.5 not realized)'],
 ['DQ','Resampling tolerance Δτ','50 ms (corpus on exact 10 Hz grid; grouped by integer dwell index)'],
 ['DQ','Track-initiation quality gate q_init','0.45'],
 ['STR','Recurrent hidden size','8 (attended descriptor dim; BiRNN of Sec. 3.5 replaced by linear-softmax proxy)'],
 ['STR','Number of feature groups G','4 (kinematic, spectral, trajectory, quality)'],
 ['STR','Dropout rate','0 (deterministic ensemble; no MC dropout)'],
 ['UAC','Ensemble size M','5'],
 ['UAC','Monte Carlo samples L','1 (deterministic ensemble; MC integration not used)'],
 ['UAC','Optimizer / learning rate','none (analytical prototype logits; no gradient training in reference impl.)'],
 ['UAC','Batch size','n/a (no training)'],
 ['UAC','Calibration bins B','10 (equal width)'],
 ['UAC','Regularization / ensemble diversity','member weight perturbation N(0, 0.20)'],
 ['UAC','Temperature T','1.35'],
 ['AMT','Covariance inflation ζ','9.0 m^2 base, x(1 + 3(1-q)) (up to 4x at q->0)'],
 ['AMT','Uncertainty tempering γ','3.0'],
 ['AMT','Class forgetting factor','alpha = 0.15 + 0.35 q (quality-adaptive)'],
 ['AMT','Association gate','chi^2(3 dof) = 16.0  (P_G ~ 0.9989)'],
 ['AMT','Process noise q','4.0'],
 ['AMT','Confirmation / deletion logic','3-of-3 confirm; delete after 8 consecutive misses'],
]
write_csv('table2_hyperparameters.csv',['Component','Parameter','Value'],t2)
write_latex('table2_hyperparameters.tex','Hyperparameter configuration of the reference UST-Fuse implementation (values read directly from the S2 source; italicised notes mark parameters realised differently from the idealised architecture of Section 3).','tab:hyperparameters',['Component','Parameter','Value'],t2)

# ---- Table 3: corpus composition (reference seed 20260730; per-seed means over 30 reps in notes) ----
t3=[
 ['Scenario families','Individual / Simultaneous / Sequential / Combined (100 / 100 / 100 / 100)'],
 ['Number of scenarios','400 per repetition (30 repetitions)'],
 ['Total radar dwells (scenario-frames)','89,180 (reference seed); 217,932 ground-truth target-dwell rows'],
 ['Total measurements','203,464 (reference seed); mean 203,125 +/- 2,910 over 30 seeds'],
 ['Total target-tracks (trajectories)','1,151 (reference seed); ~1,150 per seed'],
 ['Target classes','UAV, BIRD, OTHER (3 classes)'],
 ['Class balance (trajectories)','UAV:BIRD:OTHER = 696:300:155 ~ 0.605 : 0.261 : 0.135'],
 ['Maximum simultaneous targets','6'],
 ['Target velocity','instantaneous 0-119 m/s (nominal cruise 4-80 m/s)'],
 ['Target altitude','5-399 m (nominal cruise 20-399 m)'],
 ['Approach direction','full 360 deg azimuth (-180..180 deg)'],
 ['Manoeuvre types','straight, weaving, hover, diving'],
 ['Signal-to-noise ratio','approx -6 to 66 dB (bulk of detections -5..30 dB)'],
 ['Clutter intensity lambda','0.8 false alarms per dwell (Poisson); ~71k false alarms/seed'],
 ['Observation completeness rho','0.70-1.00 per detection; trajectory-level 0.40-1.00 (incl. missed dwells)'],
 ['Measurement update rate','10 Hz (dwell interval 0.1 s)'],
]
write_csv('table3_corpus.csv',['Property','Value / range'],t3)
write_latex('table3_corpus.tex','Composition of the RadarTwin-UAV scenario corpus and range of controlled factors (reference seed 20260730).','tab:corpus',['Property','Value / range'],t3)
print('static tables written:')
for f in sorted(os.listdir('tables')):
    if f.endswith('.csv') and ('table' in f or 'environment' in f): print('  ',f)
